// export { default as Container } from './ExampleContainer'
export { default as StartupContainer } from './StartupContainer'
export { default as Login } from './Auth/Login'
export { default as Register } from './Auth/Register'
export { default as Home } from './Home'
export { default as Bookings } from './Bookings'
export { default as Favorites } from './Favorites'
export { default as Settings } from './Settings'
